USE UTNAppDB;

DROP PROCEDURE IF EXISTS  GetStudentById;

DELIMITER //

CREATE PROCEDURE GetStudentById
(
	IN IdStudentDBParam INT
)
BEGIN
	SELECT * FROM Student WHERE IdStudentDB = IdStudentDBParam;
END //

DELIMITER ;