USE UTNAppDB;

DROP PROCEDURE IF EXISTS  GetStudentById;

DELIMITER //

CREATE PROCEDURE GetStudentById
(
	IdStudentParam INT
)
BEGIN
	SELECT * FROM Student WHERE IdStudent = IdStudentParam;
END //

DELIMITER ;